(ns spine.rules
  "Compile a project's decisions.edn into a deterministic lint projection:
  a banned-pattern list (regex + message + level) plus a commit-category
  allowlist. One-way projection: same decisions, same bytes. No Vale, no
  YAML; the output is EDN that spine.lint loads directly.

  decisions.edn shape:
    {:banned-categories [{:id :em-dash :pattern \"...\" :message \"...\"}
                          {:term \"LegacyName\"}]      ; shorthand: bare term
     :naming {<kind> \"<regex>\"}                      ; -> a banned-mismatch rule
     :commit-categories [\"Build\" \"Tests\" \"Fix\" ...]}
  "
  (:require [babashka.fs :as fs]
            [clojure.edn :as edn]
            [clojure.pprint :as pprint]
            [clojure.string :as str]
            [spine.core :as core]))

(def ^:private header ";; generated by bb compile-rules; do not edit; edit decisions.edn and re-run\n")

(defn- normalize-ban
  "A banned entry is either a map {:id :pattern :message :level} or a bare
  string term (banned category/word). Produce a uniform rule map."
  [entry]
  (cond
    (map? entry)    entry
    (string? entry) {:id (keyword (str/lower-case
                                 (str/replace entry #"[^a-zA-Z0-9]+" "-")))
                     :pattern (str/re-quote-replacement entry)
                     :message (str "Banned category: " entry)
                     :level :minor}
    :else           nil))

(defn- banned-patterns
  "Project :banned-categories into a sorted, deduped list of rule maps."
  [decisions]
  (->> (:banned-categories decisions)
       (keep normalize-ban)
       (concat
        (for [[kind re-str] (:naming decisions)]
          {:id (keyword (str "naming-" (name kind)))
           :pattern re-str
           :message (str "Naming ruling for " (name kind) " violated")
           :level :warning}))
       (sort-by (comp str :id))
       distinct
       vec))

(defn- commit-categories
  "Project :commit-categories into a sorted, deduped vector, or nil."
  [decisions]
  (when-let [cs (seq (:commit-categories decisions))]
    (->> cs distinct sort vec)))

(defn project
  "Pure projection of decisions into {:banned-patterns [...]}. Deterministic:
  same decisions, same output. (commit-categories is emitted separately.)"
  [decisions]
  {:banned-patterns (banned-patterns decisions)})

(defn emit!
  "Write the projections under styles-dir: lint-rules.edn (banned patterns,
  consumed by spine.lint) and commit-categories.edn (consumed by the commit
  recipe). Returns {:files [relative-paths...]}."
  [decisions styles-dir]
  (let [bans (banned-patterns decisions)
        cats (commit-categories decisions)
        outputs (cond-> {"lint-rules.edn"
                         (str header (with-out-str
                                       (pprint/pprint bans)))}
                  (some? cats)
                  (assoc "commit-categories.edn"
                         (str header (with-out-str
                                       (pprint/pprint cats)))))]
    (fs/create-dirs styles-dir)
    (doseq [[rel content] outputs]
      (spit (str (fs/path styles-dir rel)) content))
    {:files (vec (sort (keys outputs)))}))

(defn- find-decisions [root]
  (or (core/read-edn (str (fs/path (core/working-dir root) "decisions.edn")))
      (core/read-edn (str (fs/path root "decisions.edn")))
      (throw (ex-info "no decisions.edn found under the spine working dir or ./decisions.edn"
                      {:root root}))))

(defn -main
  "bb compile-rules [ROOT] [STYLES-DIR] - reads decisions.edn (root, default
  .) and writes lint-rules.edn (+ commit-categories.edn) into styles-dir
  (default <working-dir>/rules)."
  [& args]
  (let [root (or (first args) ".")
        styles-dir (or (second args)
                       (str (fs/path (core/working-dir root) "rules")))
        decisions (find-decisions root)
        {:keys [files]} (emit! decisions (fs/path styles-dir))]
    (doseq [f files] (println "wrote" (str (fs/path styles-dir f))))))
